### ISSUE TITLE
The bean 'dubboConfigConfiguration.Single', defined in null, could not be registered

### ISSUE THREAD

**Issue by zhengqigo** [apache/incubator-dubbo-spring-boot-project#476]
OS: Windows 10
JDK: 1.8
Dubbo: 2.7.1
Dubbo-Starter: 2.7.0

***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'dubboConfigConfiguration.Single', defined in null, could not be registered. A bean with that name has already been defined in null and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

**Comment by zhengqigo** [comment]
@mercyblitz

**Comment by zhangfei9734** [comment]
spring.properties  set spring.main.allow-bean-definition-overriding=true

**Comment by mercyblitz** [comment]
Did you use Spring Boot 2.1.0?

**Comment by zhengqigo** [comment]
Spring Boot 2.1.3

**Comment by Yahiko-r** [comment]
I had the same problem. Then i remove  @EnableDubbo annotation. it's OK

**Comment by skycyang** [comment]
I had the same problem

**Comment by lazycece** [comment]
I also have the same problem, when i change the dubbo's version from 2.7.0 to 2.7.1 （because the dubbo-2.7.0 has a bug "[incubator-dubbo/issues/3555](https://github.com/apache/incubator-dubbo/issues/3555)" which be fix on 2.7.1）,then i think maybe the dubbo-starter shuld be alse 2.7.1, but  i cannot use the dubbo-starter-2.7.1(the  dependency will not be found)

**Comment by mercyblitz** [comment]
Did you try add property `spring.properties set spring.main.allow-bean-definition-overriding=true` ?

**Comment by mercyblitz** [comment]
See https://github.com/apache/incubator-dubbo/issues/3193
