### ISSUE TITLE
请问如何配置一个项目既是消费者，又是提供者

### ISSUE THREAD

**Issue by oawang** [apache/incubator-dubbo-spring-boot-project#66]
dubbo.application.id = dubbo-provider-demo
dubbo.application.name = dubbo-provider-demo
这一句是用来配置是消费者还是提供者而，那如果我现在有一个服务既需要当提供者，又需要当消费者，那该怎么配置

**Comment by ralf0131** [comment]
Hi, Welcome!

Would you please consider ask in English? Since this project is moved to ASF repo, we hope it is understandable by people all over the world so that everyone can join to discuss.

Meanwhile, could you please ask by sending an email to dev@dubbo.incubator.apache.org, issues are used to track bugs.

**Comment by oawang** [comment]
Could you tell me how to configure a project is both consumers and providers. 
eg.
dubbo.application.id = dubbo-provider-demo
dubbo.application.name = dubbo-provider-demo

dubbo.application.id = dubbo-consumer-demo
dubbo.application.name = dubbo-consumer-demo

**Comment by luffyke** [comment]
@oawang you can use the same id and name for both consumers and providers.
```
dubbo.application.id = dubbo-demo
dubbo.application.name = dubbo-demo
```

**Comment by zonghaishang** [comment]
@oawang
If the same service provider and consumer are in one project, the consumer will inject from the spring context to get the provider and will not initiate a remote call.

I suggest you set :

dubbo.application.id = dubbo-provider-demo
dubbo.application.name = dubbo-provider-demo

Because remote consumer may want invoke current service.

**Comment by oawang** [comment]
OK, THS @zonghaishang @luffyke 

use xml config like this:

<dubbo:application name="sso-service-consumer" logger="slf4j" />


<dubbo:application name="sso-service-provider" logger="slf4j" />

so I want to how to use annotations means to achieve the current configuration

**Comment by oawang** [comment]
@luffyke @zonghaishang OK, ths

**Comment by luffyke** [comment]
@zonghaishang Is there any document or code i can reference to for what you say "If the same service provider and consumer are in one project, the consumer will inject from the spring context to get the provider and will not initiate a remote invocation"?
What i concern is that we use provider and consumer in the same project, and i found that many user have such requirement.

**Comment by zonghaishang** [comment]
@luffyke
I have written a demo for you. 
[simpledemo.zip](https://github.com/apache/incubator-dubbo-spring-boot-project/files/1836229/simpledemo.zip)

f the same service provider and consumer are in one project, the consumer will not initiate a remote invocation because of use injvm protocol. 

![image](https://user-images.githubusercontent.com/15549777/37753301-44e04d12-2dd7-11e8-8027-4b9aabd08ea1.png)
![image](https://user-images.githubusercontent.com/15549777/37753333-5ffeaba2-2dd7-11e8-8526-088cef8f1f22.png)


You can debug my demo to see that, Hopefully I can helpe to you

**Comment by luffyke** [comment]
@zonghaishang I use dubbo-spring-boot-project and zookeeper as registry, but consumer don't like you said run injvm protocol, it's as my expected run zookeeper protocol.
dubbo-spring-boot-project version 0.1.0, dubbo version 2.5.10

**Comment by zonghaishang** [comment]
@luffyke
Please send me your demo project, thanks.
