### ISSUE TITLE
希望尽快把spring boot版本的集成文档补齐，特别是注册的一些参数解释，项目集成了一下，并没有成功。

### ISSUE THREAD

**Issue by bbqtk** [apache/incubator-dubbo-spring-boot-project#69]
所以当前项目进度看来，并没有可以到发布稳定版本的时候，感觉这次的发布很草率。

**Comment by lovepoem** [comment]
Please attach some Exception logs.

**Comment by ralf0131** [comment]
Hi, Welcome!

Would you please consider ask in English? Since this project is moved to ASF repo, we hope it is understandable by people all over the world so that everyone can join to discuss.

Also, please try to ask by sending an email to dev@dubbo.incubator.apache.org , issues is used to track bugs.

**Comment by liusxg** [comment]
https://github.com/liusxg/springboot-dubbo-zookeeper-demo
consider this repo @bbqtk

**Comment by ralf0131** [comment]
@liusxg I think we can create a repository of demos and your demo can be a very good example!

**Comment by fangzongzhou** [comment]
@liusxg can u provide a demo consumer  with multle provider

**Comment by wingyiu** [comment]
请给个配置项清单 谢谢

**Comment by 15168326318** [comment]
请解答下同一个接口同时支持多个协议的配置，按最新版本也不行啊，真是急死人了。

**Comment by 15168326318** [comment]
业务组都等着我去实现呢

**Comment by 15168326318** [comment]
![image](https://user-images.githubusercontent.com/38483933/44391286-ff64b180-a561-11e8-904d-ce3595022fa8.png)
![image](https://user-images.githubusercontent.com/38483933/44391309-10adbe00-a562-11e8-94da-7f1810eb7791.png)
这样失败，没有协议。

**Comment by mercyblitz** [comment]
Duplicated issue #154
